spring:
  application:
    name: whathis

  # Multipart 설정 (파일 업로드 용량 제한)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # MySQL 데이터베이스 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true  # JPA 테이블 생성 후 data.sql 실행

  # SQL 로깅
  sql:
    init:
      mode: never

  # OPEN AI 설정
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always # AI 채팅 내역 저장 스키마 자동 생성

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# JWT 설정
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1시간

# KAKAO OAuth
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:5173/oauth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

# PortOne 설정
portone:
  api-secret: ${PORTONE_API_SECRET}

